### ISSUE TITLE
How to run the program

### ISSUE THREAD

**Issue by ethren** [Cvarier/2D-Elliptic-Mesh-Generator#1]
Hello, 
Thank you for sharing this project.
Unfortunately I could manage to run it. In the README file there is no instructions about that

Thank you

**Comment by Cvarier** [comment]
@ethren 
Thank you very much for your question and interest in my project. I've now included a section in the README which explains how to run the program. I'll also shortly add a section on building the source from scratch if you're interested in helping develop further. Please let me know if you have any more questions!
